services:
    alphaedge__fastapi:
        image: alphaedge__fastapi:latest
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: alphaedge__fastapi
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        depends_on:
            alphaedge__redis:
                condition: service_healthy
        env_file:
            - ./.env
        ports:
            - "${PORT}:${PORT}"
        environment:
            - HOST=$HOST
            - PORT=$PORT
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - REDIS_PASSWORD=$REDIS_PASSWORD
            - RABBITMQ_HOST=$RABBITMQ_HOST
            - RABBITMQ_USER=$RABBITMQ_USER
            - RABBITMQ_PASS=$RABBITMQ_PASS
        volumes:
            - .:/app
            - ./logs:/app/logs
        networks:
            - alphaedge__network
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 512M
                reservations:
                    cpus: "1"
                    memory: 256M

    alphaedge__redis:
        image: redis:latest
        container_name: alphaedge__redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "${REDIS_PORT}:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        restart: always
        networks:
            - alphaedge__network
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 256M
                reservations:
                    cpus: "0.5"
                    memory: 128M

networks:
    alphaedge__network:
        driver: bridge
        external: true
